services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    container_name: db_user
    environment:
      POSTGRES_USER: familialuna
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: usersuap
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    container_name: spring_boot_app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/usersuap
      SPRING_DATASOURCE_USERNAME: familialuna
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: 60000
      SPRING_DOCKER_COMPOSE_ENABLED: false
    depends_on:
      - db

volumes:
  postgres_data: